package com.riftos.app

import android.app.ActivityManager
import android.content.Context
import android.net.Uri
import android.os.Build
import android.os.StatFs
import android.os.SystemClock
import android.provider.OpenableColumns
import android.webkit.WebView
import org.json.JSONArray
import org.json.JSONObject
import java.io.File
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

/**
 * Privacy-limited diagnostic snapshot generated by the RiftOS Android kernel.
 *
 * This deliberately excludes secrets, Android IDs, account data, installed-app
 * lists, network identifiers, file names, and file contents. Filesystem data is
 * aggregate-only so the dump is useful for debugging without becoming a data
 * export surface.
 */
class RiftSystemDump(private val context: Context) {
    companion object {
        private const val MAX_TREE_ENTRIES = 20_000
        private const val SCHEMA = "riftos.system-dump.v1"
    }

    fun defaultFileName(): String {
        val stamp = SimpleDateFormat("yyyyMMdd-HHmmss", Locale.US).format(Date())
        return "RiftOS-system-dump-$stamp.json"
    }

    fun save(uri: Uri): JSONObject {
        val text = build().toString(2) + "\n"
        val bytes = text.toByteArray(Charsets.UTF_8)
        context.contentResolver.openOutputStream(uri, "wt")?.use { output ->
            output.write(bytes)
            output.flush()
        } ?: throw IllegalStateException("Could not open selected dump destination")

        return JSONObject()
            .put("saved", true)
            .put("name", displayName(uri) ?: "RiftOS system dump")
            .put("bytes", bytes.size)
            .put("mime", "application/json")
    }

    fun build(): JSONObject {
        val packageInfo = context.packageManager.getPackageInfo(context.packageName, 0)
        val appInfo = context.applicationInfo
        val activityManager = context.getSystemService(Context.ACTIVITY_SERVICE) as ActivityManager
        val memoryInfo = ActivityManager.MemoryInfo().also(activityManager::getMemoryInfo)
        val runtime = Runtime.getRuntime()
        val internalStats = StatFs(context.filesDir.absolutePath)
        val riftRoot = File(context.filesDir, "riftfs")
        val workspaceSandbox = File(riftRoot, "workspace")
        val webViewPackage = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            WebView.getCurrentWebViewPackage()
        } else null

        return JSONObject()
            .put("schema", SCHEMA)
            .put("generatedAtEpochMs", System.currentTimeMillis())
            .put("kernel", JSONObject()
                .put("name", "RiftOS Android Native Kernel")
                .put("bridge", "AndroidX WebMessageListener")
                .put("processUptimeMs", processUptimeMs())
                .put("availableProcessors", runtime.availableProcessors()))
            .put("app", JSONObject()
                .put("package", context.packageName)
                .put("label", appInfo.loadLabel(context.packageManager).toString())
                .put("versionName", packageInfo.versionName ?: "")
                .put("versionCode", packageVersionCode(packageInfo)))
            .put("device", JSONObject()
                .put("manufacturer", Build.MANUFACTURER)
                .put("brand", Build.BRAND)
                .put("model", Build.MODEL)
                .put("device", Build.DEVICE)
                .put("product", Build.PRODUCT)
                .put("hardware", Build.HARDWARE)
                .put("androidRelease", Build.VERSION.RELEASE)
                .put("sdk", Build.VERSION.SDK_INT)
                .put("securityPatch", Build.VERSION.SECURITY_PATCH ?: "")
                .put("supportedAbis", JSONArray(Build.SUPPORTED_ABIS.toList())))
            .put("memory", JSONObject()
                .put("systemTotalBytes", memoryInfo.totalMem)
                .put("systemAvailableBytes", memoryInfo.availMem)
                .put("systemLowMemory", memoryInfo.lowMemory)
                .put("systemLowMemoryThresholdBytes", memoryInfo.threshold)
                .put("javaHeapMaxBytes", runtime.maxMemory())
                .put("javaHeapTotalBytes", runtime.totalMemory())
                .put("javaHeapFreeBytes", runtime.freeMemory()))
            .put("storage", JSONObject()
                .put("internalTotalBytes", internalStats.totalBytes)
                .put("internalAvailableBytes", internalStats.availableBytes)
                .put("riftFs", summarizeTree(riftRoot))
                .put("workspaceSandbox", summarizeTree(workspaceSandbox)))
            .put("webView", JSONObject()
                .put("package", webViewPackage?.packageName ?: "unknown")
                .put("version", webViewPackage?.versionName ?: "unknown"))
            .put("privacy", JSONObject()
                .put("fileContentsIncluded", false)
                .put("fileNamesIncluded", false)
                .put("secretsIncluded", false)
                .put("accountDataIncluded", false)
                .put("deviceIdentifiersIncluded", false)
                .put("installedAppListIncluded", false))
    }

    private fun summarizeTree(root: File): JSONObject {
        if (!root.exists()) {
            return JSONObject()
                .put("exists", false)
                .put("files", 0)
                .put("directories", 0)
                .put("bytes", 0L)
                .put("capped", false)
        }

        var files = 0
        var directories = 0
        var bytes = 0L
        var visited = 0
        var capped = false

        fun walk(node: File) {
            if (visited >= MAX_TREE_ENTRIES) {
                capped = true
                return
            }
            visited += 1
            if (node.isDirectory) {
                if (node != root) directories += 1
                node.listFiles()?.forEach { child ->
                    if (!capped) walk(child)
                }
            } else if (node.isFile) {
                files += 1
                bytes += node.length()
            }
        }

        walk(root)
        return JSONObject()
            .put("exists", true)
            .put("files", files)
            .put("directories", directories)
            .put("bytes", bytes)
            .put("capped", capped)
            .put("entryLimit", MAX_TREE_ENTRIES)
    }

    private fun processUptimeMs(): Long =
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
            (SystemClock.elapsedRealtime() - android.os.Process.getStartUptimeMillis()).coerceAtLeast(0L)
        } else 0L

    private fun packageVersionCode(info: android.content.pm.PackageInfo): Long =
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
            info.longVersionCode
        } else {
            @Suppress("DEPRECATION")
            info.versionCode.toLong()
        }

    private fun displayName(uri: Uri): String? {
        return runCatching {
            context.contentResolver.query(uri, arrayOf(OpenableColumns.DISPLAY_NAME), null, null, null)?.use { cursor ->
                if (!cursor.moveToFirst()) return@use null
                val index = cursor.getColumnIndex(OpenableColumns.DISPLAY_NAME)
                if (index >= 0) cursor.getString(index) else null
            }
        }.getOrNull()
    }
}
